// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

function requiredEnv(name: string): string {
  const v = process.env[name];
  if (!v) throw new Error('Missing env var: ${ name }');
  return v;
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: requiredEnv('DATABASE_URL'),
  },
});
