// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
require('dotenv/config');


if (!process.env.DATABASE_URL) {
    throw new Error("Missing env DATABASE_URL");
}

module.exports = {
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
      url: process.env.DATABASE_URL,
  },
};
